import 'package:hive/hive.dart';

part 'hive.g.dart'; // This file will be generated by build_runner

@HiveType(typeId: 0) // typeId is unique for each type of Hive object
class UserModelHive {
  @HiveField(0)
  final String? uid;

  @HiveField(1)
  final String? fname;
  @HiveField(2)
  final String? lname;

  @HiveField(3)
  final int? age;

  @HiveField(4)
  final String? email;

  @HiveField(5)
  final String? profilePic;

  @HiveField(6)
  final int? phone;

  @HiveField(7)
  final int? height;

  @HiveField(8)
  final int? weight;

  @HiveField(9)
  final String? house;

  @HiveField(10)
  final String? city;

  @HiveField(11)
  final String? state;

  @HiveField(12)
  final String? family;

  @HiveField(13)
  final int? gender;

  UserModelHive({
    this.uid,
    this.fname,
    this.lname,
    this.email,
    this.profilePic,
    this.phone,
    this.height,
    this.weight,
    this.house,
    this.city,
    this.state,
    this.family,
    this.gender,
    this.age,
  });
}
